# Settings for Weapons
weapons:
  enabled: true

  old-damage: true
  disable-sweep: true
  speed: 256

# Settings for Knockback
knockback:
  enabled: false

  entities: true
  players: true

  # Restores knockback from projectiles like snowballs and fishing rods
  restore-projectiles: true

  multiplier: 1.0